# Server
server:
  host: 0.0.0.0
  port: 9090
# Logging
logging:
  log_level: INFO
# ModelSettings
model:
  path: "./model/model.onnx"
  sample_rate: 16000
  window_length: 400
  frame_length: 400
  frame_step: 160
  fft_size: 512
  n_mels: 80
  ref_value: 1.0
  amin: 1e-10
